LibraryService/LibraryService/Controllers/BooksController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using LibraryService.Domain.Core;
using LibraryService.Domain.Core.Extensions;
using LibraryService.Infrastructure.Data.Repositories;
using LibraryService.Models;
using LibraryService.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace LibraryService.Controllers
{
    [Authorize(Roles = ClaimsPrincipalExtension.LibrarianLevelString)]
    public class BooksController : BaseMvcController
    {
        private readonly BookRepo _bookRepo;
        private readonly BookGenreRepo _bookGenreRepo;
        private readonly IMapper _mapper;
        private readonly ILogger<Book> _logger;
        private readonly IBookService _bookService;

        public BooksController(IMapper mapper, ILogger<Book> logger, BookRepo bookRepo, BookGenreRepo bookGenreRepo,
            IBookService bookService)
        {
            _mapper = mapper;
            _logger = logger;
            _bookRepo = bookRepo;
            _bookGenreRepo = bookGenreRepo;
            _bookService = bookService;
        }

        public virtual async Task<IActionResult> Index()
        {
            var books = await _bookRepo.GetListQuery().Include(p => p.Publisher)
                .Include(p => p.Author)
                .Include(p => p.Genres)
                .Select(p => new BookIndexViewModel(p.Id, p.Title, p.Published, p.Publisher.Name, p.Author.FullName,
                    p.Genres.Select(g => g.Name)))
                .ToListAsync();

            return View(books);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BookEditModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var entity = _mapper.Map<Book>(model);

                    if (await _bookRepo.IsDuplicate(entity))
                    {
                        ModelState.AddModelError(nameof(Book.Title),
                            "Книга с такими характеристиками уже существует в базе");
                        throw new Exception($"{nameof(model.GetType)} duplicated record");
                    }

                    await _bookService.CreateBook(entity);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    _logger.LogError($"{nameof(Create)} {model.GetType()} exception: {ex.Message}");
                }
            }

            return View(_mapper.Map<BookEditModel>(model));
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                _logger.LogError($"{nameof(Edit)} entity {typeof(Book)} not found");
                return NotFound();
            }

            var entity = _bookRepo.GetListQuery().Include(p => p.Genres)
                .FirstOrDefault(p => p.Id == id.Value);
            if (entity == null)
            {
                return NotFound();
            }

            return View(_mapper.Map<BookEditModel>(entity));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BookEditModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var entity = _mapper.Map<Book>(model);

                    if (await _bookRepo.IsDuplicate(entity))
                    {
                        ModelState.AddModelError(nameof(Book.Title),
                            "Книга с такими характеристиками уже существует в базе");
                        throw new Exception($"{nameof(model.GetType)} duplicated record");
                    }

                    await _bookRepo.UpdateAsync(entity);
                    // Обновление жанров
                    await _bookGenreRepo.UpdateBookGeneres(entity, model.Genres);

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    _logger.LogError($"{nameof(Create)} {model.GetType()} exception: {ex.Message}");
                }
            }

            return View(_mapper.Map<BookEditModel>(model));
        }

        public virtual IActionResult Delete([FromRoute] int? id)
        {
            if (id == null) return NotFound();

            var entity = _bookRepo.GetListQuery()
                .Include(p => p.Publisher)
                .Include(p => p.Author)
                .FirstOrDefault(p => p.Id == id.Value);
            if (entity == null) return NotFound();

            return View("Delete",
                new BookIndexViewModel(entity.Id, entity.Title, entity.Published, entity.Publisher.Name,
                    entity.Author.FullName, Array.Empty<string>()));
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public virtual async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var entity = await _bookRepo.GetAsync(id);
                var result = await _bookService.DeleteBook(entity);

                return result ? RedirectToAction("Index") : RedirectToAction("Delete", id);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Delete: {ex.Message}");
                return RedirectToAction("Delete", id);
            }
        }
    }
}

LibraryService/LibraryService/Controllers/IssueController.cs
#region

using System.Linq;
using System.Threading.Tasks;
using LibraryService.Domain.Core.Extensions;
using LibraryService.Infrastructure.Data.Repositories;
using LibraryService.Models;
using LibraryService.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

#endregion

namespace LibraryService.Controllers
{
    public class IssueController : Controller
    {
        private readonly ReserveRepo _reserveRepo;
        private readonly IIssueService _issueBook;
        private readonly UsersRepo _usersRepo;
        private readonly IssueRepo _issueRepo;

        public IssueController(ReserveRepo reserveRepo, IIssueService issueBook, UsersRepo usersRepo,
            IssueRepo issueRepo)
        {
            _reserveRepo = reserveRepo;
            _issueBook = issueBook;
            _usersRepo = usersRepo;
            _issueRepo = issueRepo;
        }

        [Authorize(Roles = "Reader")]
        public async Task<IActionResult> Index()
        {
            var user = await _usersRepo.GetCurrentUser(User);
            var issues = await _issueRepo.GetIssuedBooks(user.Id).ToListAsync();

            var models = issues.Select(p => new IssueIndexViewModel(p));

            return View(models);
        }

        [HttpGet]
        [Authorize(Roles = ClaimsPrincipalExtension.LibrarianLevelString)]
        public async Task<IActionResult> ReservedBooks()
        {
            var reservedBooks = await _reserveRepo.GetReservedBooks(null)
                .Include(p => p.Book)
                .Include(p => p.User).ToListAsync();
            var models = reservedBooks.Select(p => new ReserveForIssueViewModel(p));
            return View(models);
        }

        [Authorize(Roles = ClaimsPrincipalExtension.LibrarianLevelString)]
        public async Task<IActionResult> MakeBookIssue(int idReserve)
        {
            var reserve = await _reserveRepo.GetAsync(idReserve);
            await _issueBook.MakeIssue(reserve);

            return RedirectToAction("ReservedBooks");
        }

        [HttpGet]
        [Authorize(Roles = ClaimsPrincipalExtension.LibrarianLevelString)]
        public async Task<IActionResult> IssuedBooks()
        {
            var issuedBooks = await _issueRepo.GetIssuedBooks(null)
                .Include(p => p.Book)
                .Include(p => p.User).ToListAsync();

            var models = issuedBooks.Select(p => new IssueReturnViewModel(p));
            return View(models);
        }

        [Authorize(Roles = ClaimsPrincipalExtension.LibrarianLevelString)]
        public async Task<IActionResult> ReturnBook(int idIssue)
        {
            var issue = await _issueRepo.GetAsync(idIssue);
            await _issueBook.ReturnBook(issue);
            return RedirectToAction("IssuedBooks");
        }
    }
}

LibraryService/LibraryService/Controllers/ReserveController.cs
#region

using System.Linq;
using System.Threading.Tasks;
using LibraryService.Domain.Core.Extensions;
using LibraryService.Infrastructure.Data.Repositories;
using LibraryService.Models;
using LibraryService.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

#endregion

namespace LibraryService.Controllers
{
    [Authorize(Roles = ClaimsPrincipalExtension.ReaderLevelString)]
    public class ReserveController : Controller
    {
        private readonly ReserveRepo _reserveRepo;
        private readonly IReserveService _reserveBook;
        private readonly UsersRepo _usersRepo;
        private readonly BookRepo _bookRepo;

        public ReserveController(ReserveRepo reserveRepo, IReserveService reserveBook, UsersRepo usersRepo,
            BookRepo bookRepo)
        {
            _reserveRepo = reserveRepo;
            _reserveBook = reserveBook;
            _usersRepo = usersRepo;
            _bookRepo = bookRepo;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _usersRepo.GetCurrentUser(User);
            var reserves = await _reserveRepo.GetReservedBooks(user.Id).ToListAsync();

            var models = reserves.Select(p => new ReserveIndexViewModel(p));

            return View(models);
        }

        [Authorize(Roles = "Reader")]
        public async Task<IActionResult> MakeReserve(int idBook)
        {
            var user = await _usersRepo.GetCurrentUser(User);
            var book = await _bookRepo.GetAsync(idBook);
            await _reserveBook.MakeReserve(book, user);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Reader")]
        public async Task<IActionResult> CancelReserve(int idReserve)
        {
            await _reserveBook.CancelReserve(idReserve);
            return RedirectToAction("Index");
        }
    }
}

LibraryService/LibraryService/Controllers/UsersController.cs
#region

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using LibraryService.Domain.Core;
using LibraryService.Domain.Core.Auth;
using LibraryService.Domain.Core.Extensions;
using LibraryService.Infrastructure.Data.Repositories;
using LibraryService.Models;
using LibraryService.Models.Users;
using LibraryService.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;

#endregion

namespace LibraryService.Controllers
{
    [Authorize(Roles = ClaimsPrincipalExtension.AdminLevelString)]
    public class UsersController : Controller
    {
        private readonly UsersRepo _usersRepo;
        private readonly RolesRepo _rolesRepo;
        private readonly IMapper _mapper;
        private readonly IStringLocalizer<SharedResource> _sharedLocalizer;
        private readonly ILogger<User> _logger;
        private readonly UserManager<User> _userManager;
        private readonly IUserService _userService;

        public UsersController(UsersRepo usersRepo, RolesRepo rolesRepository, IMapper mapper,
            IStringLocalizer<SharedResource> sharedLocalizer, ILogger<User> logger, UserManager<User> userManager, IUserService userService)
        {
            _usersRepo = usersRepo;
            _rolesRepo = rolesRepository;
            _mapper = mapper;
            _sharedLocalizer = sharedLocalizer;
            _logger = logger;
            _userManager = userManager;
            _userService = userService;
        }


        public async Task<IActionResult> Index()
        {
            var userViewList = new List<UserViewModel>();
            var currentUser = await _usersRepo.GetCurrentUser(User);
            var users = _usersRepo.GetListQuery().Where(p => p.Id != currentUser.Id).ToList();

            foreach (var user in users)
            {
                var userRoles = await _usersRepo.GetUserRoles(user);
                var rolesDescription = _rolesRepo.GetRolesDescription(userRoles).ToList();
                var userViewModel = _mapper.Map<UserViewModel>((user, rolesDescription));

                userViewList.Add(userViewModel);
            }

            return View(userViewList);
        }

        public virtual IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModelWithRoles entity)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var user = _mapper.Map<User>(entity);
                    var errors = ValidateUser(user);
                    if (!errors.Any())
                    {
                        await _userService.AddUser(user, entity.Roles, entity.Password);
                        return RedirectToAction("Index");
                    }

                    throw new Exception(string.Join("\n", errors.Select(p => p.Message)));
                }
                catch (Exception ex)
                {
                    return View(entity);
                }
            }

            return View(entity);
        }

        [HttpGet]
        public virtual async Task<IActionResult> EditWithRoles(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entity = await _usersRepo.GetAsync(id.Value);
            if (entity == null)
            {
                return NotFound();
            }

            var userRoles = await _usersRepo.GetUserRoles(entity);

            var userWithRoles = _mapper.Map<UserWithRoles>(entity);
            userWithRoles.Roles = userRoles;

            return View(userWithRoles);
        }

        [HttpPost]
        public async Task<IActionResult> EditWithRoles(int id, UserWithRoles model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid) return View(model);
            
            var entity = _usersRepo.GetListQuery().FirstOrDefault(p => p.Id == id);
            if (entity == null)
            {
                return NotFound();
            }

            var user = _mapper.Map(model, entity);
            user.Id = id;
            var errors = ValidateUser(user);
            if (errors.Any())
            {
                return BadRequest(errors);
            }

            try
            {
                await _userService.UpdateUser(user, model.Roles);
            }
            catch (Exception ex)
            {
                errors.Add(new ErrorInfo(ex.Message));
                return BadRequest(errors);
            }

            return RedirectToAction("Index");

        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entity = await _usersRepo.GetAsync(id.Value);
            if (entity == null)
            {
                _logger.LogError($"{nameof(Delete)} entity {typeof(User)} not found");
                return NotFound();
            }

            return View(_mapper.Map<UserViewModel>(entity));
        }

        // POST: CropsExample/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public virtual async Task<IActionResult> DeleteConfirmed(int id)
        {
            var entity = await _usersRepo.GetAsync(id);
            await _userService.RemoveUser(entity);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> ChangePassword(int idUser)
        {
            var user = await _usersRepo.GetAsync(idUser);
            if (user == null)
            {
                return View("Index");
            }

            var code = await _userManager.GeneratePasswordResetTokenAsync(user);
            var model = new ResetPasswordViewModel(idUser, code)
            {
                Email = user.Email
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ResetPasswordViewModel model)
        {
            if (!ModelState.IsValid) return View(model);
            try
            {
                await _userService.ChangePassword(model.IdUser, model.Password, model.Code);
            }
            catch
            {
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public virtual List<ErrorInfo> ValidateUser(User entity)
        {
            var res = ErrorList.GetErrors(entity);
            if (!_usersRepo.IsUnique(entity)) res.Add(new ErrorInfo(_sharedLocalizer["EntityExists"]));
            return res;
        }

        private bool EntityExists(int id)
        {
            return _usersRepo.GetListQuery().Any(e => e.Id == id);
        }
    }
}

LibraryService/LibraryService/Views/Shared/_BaseScripts.cshtml
<script>

        function getCookie(cname) {
            var name = cname + "=";
            var decodedCookie = decodeURIComponent(document.cookie);
            var ca = decodedCookie.split(';');
            for (var i = 0; i < ca.length; i++) {
                var c = ca[i];
                while (c.charAt(0) == ' ') {
                    c = c.substring(1);
                }
                if (c.indexOf(name) == 0) {
                    return c.substring(name.length, c.length);
                }
            }
            return "";
        }
        function setCookie(cname, cvalue, exdays) {
            var d = new Date();
            d.setTime(d.getTime() + (exdays * 24 * 60 * 60 * 1000));
            var expires = "expires=" + d.toUTCString();
            document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
        }
        function NavBarChange() {
            var className = $("#sidebar").attr('class');
            if (className == 'c-sidebar c-sidebar-dark c-sidebar-fixed c-sidebar-lg-show') {
                className = 'c-sidebar c-sidebar-dark c-sidebar-fixed';
                setCookie("sidebar-state", className, 7);
            }
            else {
                className = 'c-sidebar c-sidebar-dark c-sidebar-fixed c-sidebar-lg-show';
                setCookie("sidebar-state", className, 7);
            }
        }

        function refreshValidator(form){
            form.unbind();
            form.data("validator", null);
            $.validator.unobtrusive.parse(document);
        }
        
        $(document).ready(function () {
            var className = $("body").attr('class');
            var cookieNavBar = getCookie("sidebar-state");
            var accordionSidebar = $("#sidebar");
            if (cookieNavBar == "") {
                cookieNavBar = 'c-sidebar c-sidebar-dark c-sidebar-fixed c-sidebar-lg-show';
            }

            if (className != cookieNavBar) {
                accordionSidebar.removeClass(className).addClass(cookieNavBar);
            }
        });

        function initTable(div_id) {
            var table = $("body").find('#' + div_id);
            table.addClass("table-sm display no-wrap table-hover");
            table.attr("width", "100%");
            return table.DataTable({
                responsive: true,
                select: 'single',
                "language": {
                    "processing": "Подождите...",
                    "search": "Поиск:",
                    "lengthMenu": "Показать _MENU_ записей",
                    "info": "Записи с _START_ до _END_ из _TOTAL_ записей",
                    "infoEmpty": "Записи с 0 до 0 из 0 записей",
                    "infoFiltered": "(отфильтровано из _MAX_ записей)",
                    "infoPostFix": "",
                    "loadingRecords": "Загрузка записей...",
                    "zeroRecords": "Записи отсутствуют.",
                    "emptyTable": "В таблице отсутствуют данные",
                    "paginate": {
                        "first": "Первая",
                        "previous": "Пред.",
                        "next": "След.",
                        "last": "Посл."
                    },
                    "aria": {
                        "sortAscending": ": активировать для сортировки столбца по возрастанию",
                        "sortDescending": ": активировать для сортировки столбца по убыванию"
                    }
                },
                "columnDefs": [
                    {
                        "targets": [ 0 ],
                        "visible": false,
                        "searchable": false
                    }
                ]
            });                        
        }
        function ajaxCreate(action, controller, loadFunction, data, refresh) {

            $.ajax({
                url: "/" + controller + "/" + action,
                type: "GET",
                data: data,
                success: function (result) {
                    loadFunction(result, refresh);
                },
                error: function (error) {
                    console.log("ajax Create error", error);
                    $("#res").html(error);
                }
            });
        }
        function ajaxEdit(action, controller, id, loadFunction, data, refresh) {

            $.ajax({
                url: "/" + controller + "/" + action + "/" + id,
                type: "GET",
                data: data,
                success: function (result) {
                    loadFunction(result, refresh);
                },
                error: function (error) {
                    console.log("ajax Edit error", error);
                    $("#res").html(error);
                }
            });
        }
        function ajaxDelete(action, controller, id, loadFunction, data, refresh) {

            $.ajax({
                url: "/" + controller + "/" + action + "/" + id,
                type: "GET",
                data: data,
                success: function (result) {
                    loadFunction(result, refresh);
                },
                error: function (error) {
                    console.log("ajax Delete error", error);
                    $("#res").html(error);
                }
            });
        }
        
        
        $(document).submit('form',
            function (e) {
                var submitbtn = $('input.btn');
                value = submitbtn.attr("value");
                submitbtn.prop("disabled", "disabled");
            });

        function ActivateButton() {
            var submitbtn = $('input.btn');
            submitbtn.prop("disabled", false);
        }
</script>

LibraryService/LibraryService/Views/Shared/_Footer.cshtml
<footer style="display:none;">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            @await Html.PartialAsync("_SelectLanguagePartial")
        </div>
    </div>
</footer>

LibraryService/LibraryService/Views/Shared/_FooterScripts.cshtml
<script src="~/node_modules/@@coreui/coreui/dist/js/coreui.bundle.min.js"></script>
<!--[if IE]><!-->
<script src="~/node_modules/@@coreui/icons/js/svgxuse.min.js"></script>
<!--<![endif]-->

<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.20/af-2.3.4/b-1.6.1/cr-1.5.2/fc-3.3.0/fh-3.1.6/kt-2.5.1/r-2.2.3/rg-1.1.1/rr-1.2.6/sc-2.0.1/sl-1.3.1/datatables.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.13.0/js/standalone/selectize.min.js" integrity="sha512-WIqmTz2P0Ei2a6Fu5gEe7rXo0cyvpLHGKcOWLkqmZSREr8AjblAQSFYt+T/dgYyPz4+alSHpLS0XkezN4VpsLg==" crossorigin="anonymous"></script>
<script type="text/javascript" src="~/node_modules/moment/moment.js"></script>

<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

LibraryService/LibraryService/Views/Shared/_HeaderScripts.cshtml
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.20/af-2.3.4/b-1.6.1/cr-1.5.2/fc-3.3.0/fh-3.1.6/kt-2.5.1/r-2.2.3/rg-1.1.1/rr-1.2.6/sc-2.0.1/sl-1.3.1/datatables.min.css"/>

<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.13.0/css/selectize.bootstrap4.min.css" integrity="sha512-qktYcs1jG0pnuA/ytX0UPY7p+g/cgWZxhNv7T5tjUm6Cc0T+SftVd4PfzBOeZ/mq2an7+8SrDyA7a9u3Uh9wpw==" crossorigin="anonymous" />
<!-- jquery latest version -->
<script
    src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
    crossorigin="anonymous"></script>

<link href="~/node_modules/pnotify/dist/PNotifyBrightTheme.css" rel="stylesheet" type="text/css"/>

<!-- Core plugin JavaScript-->
<script src="~/node_modules/jquery-ajax-unobtrusive/dist/jquery.unobtrusive-ajax.min.js"></script>

<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

<script src="~/node_modules/pnotify/dist/iife/PNotify.js"></script>
<script src="~/node_modules/pnotify/dist/iife/PNotifyButtons.js"></script>

<link href="~/node_modules/@@coreui/coreui/dist/css/coreui.min.css" rel="stylesheet">

LibraryService/LibraryService/Views/Shared/_SideBarPartial.cshtml
@using LibraryService.Domain.Core.Extensions
<div class="c-sidebar c-sidebar-dark c-sidebar-fixed c-sidebar-lg-show" id="sidebar">
    <div class="c-sidebar-brand d-lg-down-none">
        <h3 class="c-sidebar-brand-full" width="118" height="46" alt="Logo">
            Libro
        </h3>
        <h4 class="c-sidebar-brand-minimized" width="46" height="46" alt="Logo">
            L
        </h4>
    </div>
    <ul class="c-sidebar-nav">
        <li class="c-sidebar-nav-item">
            <a class="c-sidebar-nav-link" href="@Url.Action("Index", "Dashboard")">
                <svg class="c-sidebar-nav-icon">
                    <use xlink:href="../node_modules/@@coreui/icons/sprites/free.svg#cil-puzzle"></use>
                </svg> Главная
            </a>
        </li>
        @if (User.AdminLevelAccess())
        {
            <li class="c-sidebar-nav-title">Администрирование</li>
            <li class="c-sidebar-nav-item">
                <a class="c-sidebar-nav-link" href="@Url.Action("Index", "Users")">
                    <svg class="c-sidebar-nav-icon">
                        <use xlink:href="../node_modules/@@coreui/icons/sprites/free.svg#cil-group"></use>
                    </svg> Пользователи
                </a>
            </li>
            <li class="c-sidebar-nav-item">
                <a class="c-sidebar-nav-link" href="@Url.Action("Index", "Genres")">
                    <svg class="c-sidebar-nav-icon">
                        <use xlink:href="../node_modules/@@coreui/icons/sprites/free.svg#cil-tags"></use>
                    </svg> Жанры
                </a>
            </li>
            <li class="c-sidebar-nav-item">
                <a class="c-sidebar-nav-link" href="@Url.Action("Index", "Publishers")">
                    <svg class="c-sidebar-nav-icon">
                        <use xlink:href="../node_modules/@@coreui/icons/sprites/free.svg#cil-institution"></use>
                    </svg> Издатели
                </a>
            </li>
            <li class="c-sidebar-nav-item">
                <a class="c-sidebar-nav-link" href="@Url.Action("Index", "Authors")">
                    <svg class="c-sidebar-nav-icon">
                        <use xlink:href="../node_modules/@@coreui/icons/sprites/free.svg#cil-contact"></use>
                    </svg> Авторы
                </a>
            </li>
        }
        @if (User.LibrarianLevelAccess())
        {
            <li class="c-sidebar-nav-title">Управление библиотекой</li>
            <li class="c-sidebar-nav-item">
                <a class="c-sidebar-nav-link" href="@Url.Action("Index", "Books")">
                    <svg class="c-sidebar-nav-icon">
                        <use xlink:href="../node_modules/@@coreui/icons/sprites/free.svg#cil-book"></use>
                    </svg> Книги
                </a>
            </li>
            <li class="c-sidebar-nav-item">
                <a class="c-sidebar-nav-link" href="@Url.Action("IssuedBooks", "Issue")">
                    <svg class="c-sidebar-nav-icon">
                        <use xlink:href="../node_modules/@@coreui/icons/sprites/free.svg#cil-action-undo"></use>
                    </svg> Прием книг
                </a>
            </li>
            <li class="c-sidebar-nav-item">
                <a class="c-sidebar-nav-link" href="@Url.Action("ReservedBooks", "Issue")">
                    <svg class="c-sidebar-nav-icon">
                        <use xlink:href="../node_modules/@@coreui/icons/sprites/free.svg#cil-action-redo"></use>
                    </svg> Выдача книг
                </a>
            </li>
        }
        @if (User.ReaderLevelAccess())
        {
            <li class="c-sidebar-nav-title">Каталог книг</li>
            <li class="c-sidebar-nav-item">
                <a class="c-sidebar-nav-link" href="@Url.Action("Index", "BookSearch")">
                    <svg class="c-sidebar-nav-icon">
                        <use xlink:href="../node_modules/@@coreui/icons/sprites/free.svg#cil-search"></use>
                    </svg> Поиск книг
                </a>
            </li>
            @if (User.IsReader())
            {
                <li class="c-sidebar-nav-item">
                    <a class="c-sidebar-nav-link" href="@Url.Action("Index", "Reserve")">
                        <svg class="c-sidebar-nav-icon">
                            <use xlink:href="../node_modules/@@coreui/icons/sprites/free.svg#cil-bookmark"></use>
                        </svg> Забронированные
                    </a>
                </li>

                <li class="c-sidebar-nav-item">
                    <a class="c-sidebar-nav-link" href="@Url.Action("Index", "Issue")">
                        <svg class="c-sidebar-nav-icon">
                            <use xlink:href="../node_modules/@@coreui/icons/sprites/free.svg#cil-library"></use>
                        </svg> Выданные
                    </a>
                </li>
            }
        }
    </ul>
    <button class="c-sidebar-minimizer c-class-toggler" type="button" data-target="_parent" data-class="c-sidebar-minimized"></button>
</div>